# Generated by Django 4.1.3 on 2022-11-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phaddress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='phone_number_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phones',
            name='phone_number_2',
            field=models.IntegerField(),
        ),
    ]
